export interface SkillDefinition {
  name: string;
  slug: string;
  category: string;
  description: string;
  instructions: string;
  inputFields: { name: string; type: string; description: string; required: boolean }[];
  outputFormat: string;
  examples: { input: string; output: string }[];
  knowledgeFiles: string[];
  tier: string;
  department: string;
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.trim() ? pad + line : ""))
    .join("\n");
}

function yamlString(s: string): string {
  if (s.includes("\n") || s.includes(": ") || s.includes("#") || s.length > 80) {
    return "|\n" + indent(s, 2);
  }
  if (s.includes('"') && !s.includes("'")) return `'${s}'`;
  if (s.includes("'") || s.includes('"') || /^[{[\]%@&*!|>]/.test(s)) {
    return `"${s.replace(/"/g, '\\"')}"`;
  }
  return s;
}

export function generateSkillYAML(skill: SkillDefinition): string {
  const lines: string[] = [];

  lines.push(`# Claude Skill: ${skill.name}`);
  lines.push(`# Category: ${skill.category}`);
  lines.push(`# Department: ${skill.department} | Tier: ${skill.tier}`);
  lines.push(`# Generated by OrientPrint Skill Creator`);
  lines.push("");
  lines.push(`name: ${yamlString(skill.slug)}`);
  lines.push(`title: ${yamlString(skill.name)}`);
  lines.push(`description: ${yamlString(skill.description)}`);
  lines.push("");

  lines.push("instructions: |");
  skill.instructions.split("\n").forEach((line) => {
    lines.push("  " + line);
  });
  lines.push("");

  if (skill.inputFields.length > 0) {
    lines.push("input_schema:");
    lines.push("  type: object");
    lines.push("  properties:");
    skill.inputFields.forEach((field) => {
      lines.push(`    ${field.name}:`);
      lines.push(`      type: ${field.type}`);
      lines.push(`      description: ${yamlString(field.description)}`);
    });
    const required = skill.inputFields.filter((f) => f.required).map((f) => f.name);
    if (required.length > 0) {
      lines.push("  required:");
      required.forEach((r) => lines.push(`    - ${r}`));
    }
    lines.push("");
  }

  if (skill.outputFormat) {
    lines.push(`output_format: ${yamlString(skill.outputFormat)}`);
    lines.push("");
  }

  if (skill.knowledgeFiles.length > 0) {
    lines.push("knowledge_files:");
    skill.knowledgeFiles.forEach((f) => {
      lines.push(`  - ${yamlString(f)}`);
    });
    lines.push("");
  }

  if (skill.examples.length > 0) {
    lines.push("examples:");
    skill.examples.forEach((ex, i) => {
      lines.push(`  - name: Example ${i + 1}`);
      lines.push(`    input: ${yamlString(ex.input)}`);
      lines.push(`    output: ${yamlString(ex.output)}`);
    });
    lines.push("");
  }

  lines.push("metadata:");
  lines.push(`  category: ${yamlString(skill.category)}`);
  lines.push(`  department: ${yamlString(skill.department)}`);
  lines.push(`  tier: ${skill.tier}`);

  return lines.join("\n") + "\n";
}

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
